// <auto-generated />
using System;
using Fluently.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fluently.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918115703_AddTaskListsAndTasks")]
    partial class AddTaskListsAndTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fluently.API.Models.QuestionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AlternativeTranslations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasComment("Traduções em português das cinco alternativas, na mesma ordem das alternativas.");

                    b.PrimitiveCollection<string[]>("Alternatives")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AwardedXp")
                        .HasColumnType("integer");

                    b.Property<int>("BaseXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContextFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CorrectAlternativeIndex")
                        .HasColumnType("integer")
                        .HasComment("Índice de 1 a 5 da alternativa correta.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QuestionTranslation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Tradução para português da frase apresentada na questão.");

                    b.Property<int?>("StreakAfterAnswer")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmittedAlternativeIndex")
                        .HasColumnType("integer")
                        .HasComment("Índice de 1 a 5 da alternativa selecionada pelo usuário.");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"AnsweredAt\" IS NULL");

                    b.HasIndex("UserId", "ContextFingerprint")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Questions", t =>
                        {
                            t.HasCheckConstraint("CK_Questions_AwardedXp", "\"AwardedXp\" IS NULL OR \"AwardedXp\" >= 0");

                            t.HasCheckConstraint("CK_Questions_BaseXp", "\"BaseXp\" > 0");

                            t.HasCheckConstraint("CK_Questions_CorrectAlternativeIndex", "\"CorrectAlternativeIndex\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Questions_StreakAfterAnswer", "\"StreakAfterAnswer\" IS NULL OR \"StreakAfterAnswer\" >= 0");

                            t.HasCheckConstraint("CK_Questions_SubmittedAlternativeIndex", "\"SubmittedAlternativeIndex\" IS NULL OR \"SubmittedAlternativeIndex\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Fluently.API.Models.TaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsCompleted", "DueDate");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Fluently.API.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Biografia utilizada como contexto para gerar questões personalizadas.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("DailyXpGoal")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Proficiency")
                        .HasColumnType("integer")
                        .HasComment("1 = A1; 2 = A2; 3 = B1; 4 = B2; 5 = C1; 6 = C2");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("text");

                    b.Property<long>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("TotalXp", "CreatedAt");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_CurrentStreak", "\"CurrentStreak\" >= 0");

                            t.HasCheckConstraint("CK_Users_TotalXp", "\"TotalXp\" >= 0");
                        });
                });

            modelBuilder.Entity("Fluently.API.Models.QuestionModel", b =>
                {
                    b.HasOne("Fluently.API.Models.UserModel", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fluently.API.Models.TaskModel", b =>
                {
                    b.HasOne("Fluently.API.Models.UserModel", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fluently.API.Models.UserModel", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
